# Generated by Django 5.0.1 on 2024-08-14 19:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_type', models.CharField(choices=[('heavy', 'Heavy'), ('dehati', 'Dehati'), ('light', 'Light'), ('teena', 'Teena'), ('dust', 'Dust')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_type', models.CharField(choices=[('heavy', 'Heavy'), ('dehati', 'Dehati'), ('light', 'Light'), ('teena', 'Teena'), ('dust', 'Dust')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_landed_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_recived', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carrier_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('missclenous', models.DecimalField(decimal_places=2, max_digits=10)),
                ('roadclearance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food', models.DecimalField(decimal_places=2, max_digits=10)),
                ('site_visit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('petrol', models.DecimalField(decimal_places=2, max_digits=10)),
                ('toll_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='core.buyer')),
                ('purchases', models.ManyToManyField(related_name='invoices', to='core.purchase')),
                ('sales', models.ManyToManyField(related_name='invoices', to='core.sale')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='core.seller')),
            ],
        ),
    ]
