# Generated by Django 5.0.2 on 2025-01-12 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='purchases',
        ),
        migrations.AddField(
            model_name='purchase',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.invoice'),
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_type', models.CharField(choices=[('heavy', 'Heavy'), ('dehati', 'Dehati'), ('light', 'Light'), ('teena', 'Teena'), ('dust', 'Dust')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
