# Generated by Django 5.0.2 on 2025-01-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_invoice_sales_remove_invoice_purchases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
