# Generated by Django 5.0.2 on 2025-01-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_purchase_date_alter_sell_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name_plural': 'purchases'},
        ),
        migrations.AlterModelOptions(
            name='sell',
            options={'verbose_name_plural': 'sells'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchases',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='core.purchase'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='core.sell'),
        ),
    ]
