# Generated by Django 5.0.2 on 2025-01-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_buyer_address_alter_buyer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total_landed_cost',
            new_name='landed_cost',
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
