# Generated by Django 5.0.2 on 2025-01-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_total_landed_cost_invoice_landed_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='total_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='sell',
            old_name='total_amount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='advance_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='dues',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
