# Generated by Django 5.0.2 on 2025-02-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_purchase_amount_alter_purchase_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sell',
            options={},
        ),
    ]
