# Generated by Django 5.0.2 on 2025-02-05 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_alter_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('landed_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('miscellaneous', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('miscellaneous_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('carrier_charge_per_kilo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carrier_charge_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.invoice')),
            ],
        ),
    ]
